<a href="https://colab.research.google.com/github/StephenRajva/Data-Science-Classwork/blob/main/27th_Jan_DS_Class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Stephen Raj V.A [RA2311042010042]

Create a Numpy using Example
N dimensional in numpy with an example
To generate a range of value from 12 to 15 with step value is 3
Explain the Shape of 2d array and the size with example
reshape the value of [15 to 30]


### 1. Create a NumPy array using an example

In [ ]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


### 2. N-dimensional array in NumPy with an example

In [ ]:
import numpy as np

# Creating a 2D NumPy array (matrix)
array_2d = np.array([[10, 20, 30], [40, 50, 60]])
print("\n2D Array:\n", array_2d)

# Creating a 3D NumPy array
array_3d = np.array([[[1, 2,], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Array:\n", array_3d)


2D Array:
 [[10 20 30]
 [40 50 60]]

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### 3. Generate a range of values from 12 to 15 with a step value of 3

In [ ]:
import numpy as np

# Using np.arange to generate a range of values
# np.arange(start, stop, step)
# The 'stop' value is exclusive, so to include 15, we might need to adjust based on step.
# With a step of 3, starting at 12, the next value would be 15.
# To generate 12 and 15, the stop value should be greater than 15 (e.g., 16).
range_array = np.arange(12, 16, 3)
print("Range from 12 to 15 with step 3:", range_array)

Range from 12 to 15 with step 3: [12 15]


### 4. Explain the shape and size of a 2D array with an example

In [ ]:
import numpy as np

# Create a 2D array
example_2d_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Example 2D Array:\n", example_2d_array)

# Shape of the array
# The 'shape' attribute returns a tuple indicating the size of the array in each dimension.
# For a 2D array, it's (rows, columns).
print("\nShape of the array (rows, columns):", example_2d_array.shape)

# Size of the array
# The 'size' attribute returns the total number of elements in the array.
# This is equivalent to multiplying the dimensions from the shape.
print("Size of the array (total elements):", example_2d_array.size)

Example 2D Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Shape of the array (rows, columns): (3, 4)
Size of the array (total elements): 12


### 5. Reshape the values from 15 to 30

In [ ]:
import numpy as np

# First, create a 1D array with values from 15 to 30 (inclusive)
# np.arange(start, stop) where 'stop' is exclusive, so we use 31 to include 30.
original_array = np.arange(15, 31)
print("Original 1D Array (15 to 30):", original_array)
print("Original Array Shape:", original_array.shape)

# To reshape, the new shape must have the same total number of elements.
# The original array has 16 elements (30 - 15 + 1 = 16).
# We can reshape it into a 2D array, for example, 4x4 or 2x8 or 8x2.

# Reshaping to a 4x4 2D array
reshaped_array_4x4 = original_array.reshape(4, 4)
print("\nReshaped to 4x4 2D Array:\n", reshaped_array_4x4)
print("Reshaped Array Shape:", reshaped_array_4x4.shape)

# Reshaping to a 2x8 2D array
reshaped_array_2x8 = original_array.reshape(2, 8)
print("\nReshaped to 2x8 2D Array:\n", reshaped_array_2x8)
print("Reshaped Array Shape:", reshaped_array_2x8.shape)

Original 1D Array (15 to 30): [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
Original Array Shape: (16,)

Reshaped to 4x4 2D Array:
 [[15 16 17 18]
 [19 20 21 22]
 [23 24 25 26]
 [27 28 29 30]]
Reshaped Array Shape: (4, 4)

Reshaped to 2x8 2D Array:
 [[15 16 17 18 19 20 21 22]
 [23 24 25 26 27 28 29 30]]
Reshaped Array Shape: (2, 8)


Diffrence Between np.empty() and np.zero(),np.full()

### Difference Between `np.empty()`, `np.zeros()`, and `np.full()`

These three NumPy functions are used to create new arrays with a specified shape, but they differ in how they initialize the elements:

1.  **`np.zeros(shape, dtype=float)`**:
    *   **Purpose**: Creates a new array of the given `shape` and `dtype`, filled entirely with zeros.
    *   **Initialization**: Every element in the array is set to `0.0` (or `0` if `dtype` is integer).
    *   **Predictability**: The values are always predictable (all zeros).
    *   **Use Case**: Ideal when you need an array initialized to zero for accumulation or as a starting point for calculations.

2.  **`np.full(shape, fill_value, dtype=None)`**:
    *   **Purpose**: Creates a new array of the given `shape` and `dtype`, filled entirely with a specified `fill_value`.
    *   **Initialization**: Every element in the array is set to `fill_value`.
    *   **Predictability**: The values are always predictable (all equal to `fill_value`).
    *   **Use Case**: Useful when you need an array initialized to a specific constant value other than zero.

3.  **`np.empty(shape, dtype=float)`**:
    *   **Purpose**: Creates a new array of the given `shape` and `dtype`, but without initializing its elements.
    *   **Initialization**: The elements are *not* set to any specific value. They contain whatever arbitrary values were already in the memory location allocated for the array.
    *   **Predictability**: The values are **unpredictable** and can vary each time you run the code.
    *   **Efficiency**: It is slightly faster than `np.zeros()` or `np.full()` because it avoids the step of writing values to memory.
    *   **Use Case**: Best used when you are immediately going to fill the array with your own data, overwriting all elements anyway. If you read from an `empty` array before writing to it, you'll get garbage values.

In [ ]:
import numpy as np

# Example with np.zeros()
print("--- np.zeros(shape=(2, 3)) ---")
zeros_array = np.zeros(shape=(2, 3))
print("Array:\n", zeros_array)
print("Description: All elements are initialized to 0.0.")

print("\n--- np.full(shape=(2, 3), fill_value=7) ---")
full_array = np.full(shape=(2, 3), fill_value=7)
print("Array:\n", full_array)
print("Description: All elements are initialized to the specified fill_value (7).")

print("\n--- np.empty(shape=(2, 3)) ---")
empty_array = np.empty(shape=(2, 3))
print("Array:\n", empty_array)
print("Description: Elements contain arbitrary, uninitialized values from memory.")

print("\n--- np.empty() run again to show unpredictable values ---")
empty_array_again = np.empty(shape=(2, 3))
print("Array (second run):\n", empty_array_again)
print("Description: Notice these values might be different from the previous np.empty() output.")

--- np.zeros(shape=(2, 3)) ---
Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Description: All elements are initialized to 0.0.

--- np.full(shape=(2, 3), fill_value=7) ---
Array:
 [[7 7 7]
 [7 7 7]]
Description: All elements are initialized to the specified fill_value (7).

--- np.empty(shape=(2, 3)) ---
Array:
 [[1.34361846e-315 0.00000000e+000 5.78415695e-317]
 [6.52265719e-310 6.52266120e-310 6.52266696e-310]]
Description: Elements contain arbitrary, uninitialized values from memory.

--- np.empty() run again to show unpredictable values ---
Array (second run):
 [[1.34361846e-315 0.00000000e+000 5.78415695e-317]
 [6.52265719e-310 6.52266120e-310 6.52266696e-310]]
Description: Notice these values might be different from the previous np.empty() output.


np.eye() and np.identity()

### Clarification on `np.i()` and Explanation of `np.identity()`

It seems there might be a slight confusion regarding `np.i()`. The function `np.i()` is not a standard or commonly used NumPy function for creating arrays. It's possible it was a typo or a misunderstanding.

However, NumPy does have `np.identity()` and `np.eye()`, which are closely related and commonly used to create identity matrices.

---

#### `np.identity(n, dtype=None)`

*   **Purpose**: Creates a square 2D array (matrix) with ones on the main diagonal and zeros everywhere else. This is known as an **identity matrix**.
*   **Key Feature**: It only takes one argument `n`, which specifies both the number of rows and columns (since it's always square).
*   **Output**: A 2D array of size `n x n`.
*   **Use Case**: Fundamental in linear algebra, often used as a neutral element in matrix multiplication (just like 1 in regular multiplication).

#### `np.eye(N, M=None, k=0, dtype=None)`

*   **Purpose**: Creates a 2D array with ones on the diagonal and zeros elsewhere. It's more general than `np.identity()`.
*   **Key Feature**: You can specify `N` (number of rows) and `M` (number of columns) independently, and `k` to choose an offset for the diagonal (0 is the main diagonal, positive `k` for diagonals above, negative `k` for diagonals below).
*   **Output**: A 2D array of size `N x M`.
*   **Use Case**: Creating non-square matrices with a diagonal of ones, or shifting the diagonal of ones.

In [ ]:
import numpy as np

print("--- np.identity(3) ---")
identity_matrix_3x3 = np.identity(3)
print("3x3 Identity Matrix:\n", identity_matrix_3x3)
print("Description: A square matrix with ones on the main diagonal and zeros elsewhere.")

print("\n--- np.identity(4, dtype=int) ---")
identity_matrix_4x4_int = np.identity(4, dtype=int)
print("4x4 Integer Identity Matrix:\n", identity_matrix_4x4_int)

print("\n--- np.eye(4, 5, k=0) (similar to identity for main diagonal) ---")
eye_matrix_main = np.eye(4, 5, k=0)
print("4x5 Eye Matrix (main diagonal):\n", eye_matrix_main)

print("\n--- np.eye(4, 5, k=1) (diagonal above main) ---")
eye_matrix_above = np.eye(4, 5, k=1)
print("4x5 Eye Matrix (diagonal above main):\n", eye_matrix_above)

print("\n--- np.eye(4, 5, k=-1) (diagonal below main) ---")
eye_matrix_below = np.eye(4, 5, k=-1)
print("4x5 Eye Matrix (diagonal below main):\n", eye_matrix_below)

--- np.identity(3) ---
3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Description: A square matrix with ones on the main diagonal and zeros elsewhere.

--- np.identity(4, dtype=int) ---
4x4 Integer Identity Matrix:
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

--- np.eye(4, 5, k=0) (similar to identity for main diagonal) ---
4x5 Eye Matrix (main diagonal):
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]

--- np.eye(4, 5, k=1) (diagonal above main) ---
4x5 Eye Matrix (diagonal above main):
 [[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

--- np.eye(4, 5, k=-1) (diagonal below main) ---
4x5 Eye Matrix (diagonal below main):
 [[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
