<a href="https://colab.research.google.com/github/StephenRajva/Data-Science-Classwork/blob/main/PYTHON_FOR_DATA_ANALYTICS_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NUMPY

NumPy is a Python library used for working with arrays.
It also has functions for working in domain of linear algebra, fourier transform, and matrices.
NumPy stands for Numerical Python.In Python we have lists that serve the purpose of arrays, but they are slow to process.
NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.
Arrays are very frequently used in data science, where speed and resources are very important.



Data Science: is a branch of computer science where we study how to store, use and analyze data for deriving information from it.

NumPy provides an N-dimensional array type, the ndarray, which describes a collection of “items” of the same type.
The items can be indexed using for example N integers.

All ndarrays are homogeneous: every item takes up the same size block of memory, and all blocks are interpreted in exactly the same way.
How each item in the array is to be interpreted is specified by a separate data-type object, one of which is associated with every array.
In addition to basic types (integers, floats, etc.), the data type objects can also represent data structures.

An item extracted from an array, e.g., by indexing, is represented by a Python object whose type is one of the array scalar types built in NumPy.
The array scalars allow easy manipulation of also more complicated arrangements of data.

In [ ]:
import numpy as np


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
x = np.array([1, 2, 3, 4])
x.shape

(4,)

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)


(2, 4)


In [ ]:
#Creating two-dimensional arrays in NumPy
array=np.arange(20).reshape(4,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.zeros((2,4))



array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((3,6))


array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
np.full((2,2), 3)

array([[3, 3],
       [3, 3]])

In [ ]:
import numpy as np
a=np.zeros((2,4))
b=np.ones((3,6))
c=np.empty((2,3))
d=np.full((2,2), 3)
e= np.eye(3,3)
f=np.linspace(0, 10, num=4)
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[3 3]
 [3 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[ 0.          3.33333333  6.66666667 10.        ]


In [ ]:
#Conversion from Python structure like lists
import numpy as np
array=np.array([4,5,6])
print(array)
list=[4,5,6]
print(list)


[4 5 6]
[4, 5, 6]


In [ ]:
#Checking Array Dimensions in NumPy
import numpy as np
a = np.array(10)
b = np.array([1,1,1,1])
c = np.array([[1, 1, 1], [2,2,2]])
d = np.array([[[1, 1, 1], [2, 2, 2]], [[3, 3, 3], [4, 4, 4]]])
print(a.ndim)  #0
print(b.ndim)  #1
print(c.ndim)  #2
print(d.ndim) #3


0
1
2
3


In [ ]:
#Higher Dimensional Arrays in NumPy
import numpy as np
arr = np.array([1, 1, 1, 1, 1], ndmin=10)
print(arr)
print('number of dimensions :', arr.ndim)


[[[[[[[[[[1 1 1 1 1]]]]]]]]]]
number of dimensions : 10
